
caption_item = {
									"@id":"",
									"name":"",
									"enabled":"TRUE",
									"duration":"37",
									"rate":{
										"timebase":"30",
										"ntsc":"FALSE"
									},
									"start":"",
									"end":"",
									"in":"",
									"out":"",
									"file":{
										"@id":"",
										"name":"",
										"pathurl":"",
										"rate":{
											"timebase":"30",
											"ntsc":"FALSE"
										},
										"duration":"37",
										"timecode":{
											"rate":{
												"timebase":"30",
												"ntsc":"FALSE"
											},
											"string":"00:00:00:00",
											"frame":"0",
											"displayformat":"NDF"
										},
										"media":{"video":{"samplecharacteristics":{
													"width":"",
													"height":""
												}}}
									}
								}