

crop_item =  {
                            "@id":"",
                            "name":"",
                            "enabled":"TRUE",
                            "duration":"",
                            "rate":{
                                "timebase":"",
                                "ntsc":"FALSE"
                            },
                            "file":{},
                                
                            "start":"",
                            "end":"",
                            "in":"",
                            "out":"",
                            "filter":[
                                {"effect":{
                                        "name":"Basic Motion",
                                        "effectid":"basic",
                                        "effectcategory":"motion",
                                        "effecttype":"motion",
                                        "mediatype":"video",
                                        "pproBypass":"false",
                                        "parameter":[
                                            {
                                                "@authoringApp":"PremierePro",
                                                "parameterid":"scale",
                                                "name":"Scale",
                                                "valuemin":"0",
                                                "valuemax":"1000",
                                                "value":"266"
                                            },
                                            {
                                                "@authoringApp":"PremierePro",
                                                "parameterid":"rotation",
                                                "name":"Rotation",
                                                "valuemin":"-8640",
                                                "valuemax":"8640",
                                                "value":"0"
                                            },
                                            {
                                                "@authoringApp":"PremierePro",
                                                "parameterid":"center",
                                                "name":"Center",
                                                "value":{
                                                    "horiz":"-0.9375",
                                                    "vert":"-0.8333333333333334"
                                                }
                                            },
                                            {
                                                "@authoringApp":"PremierePro",
                                                "parameterid":"centerOffset",
                                                "name":"Anchor Point",
                                                "value":{
                                                    "horiz":"-0.5",
                                                    "vert":"-0.5"
                                                }
                                            },
                                            {
                                                "@authoringApp":"PremierePro",
                                                "parameterid":"antiflicker",
                                                "name":"Anti-flicker Filter",
                                                "valuemin":"0",
                                                "valuemax":"1",
                                                "value":"0"
                                            }
                                        ]
                                    }},
                                {"effect":{
                                        "name":"Crop",
                                        "effectid":"crop",
                                        "effectcategory":"motion",
                                        "effecttype":"motion",
                                        "mediatype":"video",
                                        "pproBypass":"false",
                                        "parameter":[
                                            {
                                                "@authoringApp":"PremierePro",
                                                "parameterid":"left",
                                                "name":"left",
                                                "valuemin":"0",
                                                "valuemax":"100",
                                                "value":""
                                            },
                                            {
                                                "@authoringApp":"PremierePro",
                                                "parameterid":"right",
                                                "name":"right",
                                                "valuemin":"0",
                                                "valuemax":"100",
                                                "value":""
                                            },
                                            {
                                                "@authoringApp":"PremierePro",
                                                "parameterid":"top",
                                                "name":"top",
                                                "valuemin":"0",
                                                "valuemax":"100",
                                                "value":""
                                            },
                                            {
                                                "@authoringApp":"PremierePro",
                                                "parameterid":"bottom",
                                                "name":"bottom",
                                                "valuemin":"0",
                                                "valuemax":"100",
                                                "value":""
                                            }
                                        ]
                                    }}
                            ]
                        }
