
sequence_item = {"sequence":{
			"name":"",
			"duration":"",
			"rate":{
				"timebase":"",
				"ntsc":"FALSE"
			},
			"timecode":{
				"rate":{
					"timebase":"",
					"ntsc":"FALSE"
				},
				"string":"00:00:00:00",
				"frame":"0",
				"displayformat":"NDF"
			},
			"media":{
				"video":{
					"format":{"samplecharacteristics":{
							"rate":{
								"timebase":"",
								"ntsc":"FALSE"
							},
							"width":"",
							"height":"",
							"pixelaspectratio":"square"
						}},
					"track":[
						{
							"enabled":"TRUE",
							"locked":"FALSE",
							"clipitem":[]
						},
						{
							"enabled":"TRUE",
							"locked":"FALSE"
						},
						{
							"enabled":"TRUE",
							"locked":"FALSE",
							"clipitem":[]
						}
					]
				},
				"audio":{"track":{
						"enabled":"TRUE",
						"locked":"FALSE",
						"clipitem":[]
					}}
			}
		}
	}
